import os
import subprocess
import sys
import uuid
import shutil
from typing import Dict, Any, List

class SandboxExecutor:
    """
    Safely executes generated Python code inside a subprocess.
    Captures stdout, stderr, execution status, and files (like generated charts) created by the code.
    """
    def __init__(self, workspace_dir: str = None, output_dir: str = None):
        # Set default paths if not provided
        base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        
        self.workspace_dir = workspace_dir or os.path.join(base_dir, "data", "sandbox_workspace")
        self.output_dir = output_dir or os.path.join(base_dir, "data", "outputs")
        
        # Ensure directories exist
        os.makedirs(self.workspace_dir, exist_ok=True)
        os.makedirs(self.output_dir, exist_ok=True)

    def execute_code(self, code: str, timeout_seconds: int = 15) -> Dict[str, Any]:
        """
        Executes the provided python code block in a sandboxed subprocess.
        """
        # Generate a unique run ID and script path
        run_id = str(uuid.uuid4())[:8]
        script_filename = f"script_{run_id}.py"
        script_path = os.path.join(self.workspace_dir, script_filename)
        
        # Write the python code to the script file
        with open(script_path, "w", encoding="utf-8") as f:
            f.write(code)
            
        # We want to trace any files generated in the workspace dir during execution
        files_before = set(os.listdir(self.workspace_dir))
        
        # Build execution process
        try:
            # We execute python using the same interpreter running this script
            result = subprocess.run(
                [sys.executable, script_filename],
                cwd=self.workspace_dir,
                capture_output=True,
                text=True,
                timeout=timeout_seconds,
                env={**os.environ, "MPLBACKEND": "Agg"}  # Force non-interactive backend for matplotlib
            )
            
            success = result.returncode == 0
            stdout = result.stdout
            stderr = result.stderr
            returncode = result.returncode
            
        except subprocess.TimeoutExpired as e:
            success = False
            stdout = e.stdout or ""
            stderr = f"Execution timed out after {timeout_seconds} seconds."
            returncode = -1
        except Exception as e:
            success = False
            stdout = ""
            stderr = f"Failed to start execution process: {str(e)}"
            returncode = -2
            
        # Clean up the script file
        if os.path.exists(script_path):
            try:
                os.remove(script_path)
            except Exception:
                pass
                
        # Check files created during execution
        files_after = set(os.listdir(self.workspace_dir))
        new_files = files_after - files_before
        
        generated_charts = []
        for filename in new_files:
            file_path = os.path.join(self.workspace_dir, filename)
            # We are interested in images/charts generated by the code (e.g., png)
            if filename.lower().endswith(('.png', '.jpg', '.jpeg', '.svg')):
                # Move to public outputs folder with a clean unique name
                new_filename = f"{run_id}_{filename}"
                dest_path = os.path.join(self.output_dir, new_filename)
                try:
                    shutil.move(file_path, dest_path)
                    generated_charts.append(new_filename)
                except Exception as e:
                    stderr += f"\nError saving generated chart {filename}: {str(e)}"
            else:
                # Clean up any other files generated to keep workspace tidy
                if os.path.isfile(file_path):
                    try:
                        os.remove(file_path)
                    except Exception:
                        pass
                        
        return {
            "success": success,
            "stdout": stdout,
            "stderr": stderr,
            "returncode": returncode,
            "generated_charts": generated_charts,
            "run_id": run_id
        }
